pipeline {
    agent any
    stages {
        stage('SCM checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/edgaregonzalez/devops-63703.git'
            }
        }
        stage('cambio de directorio de trabajo') {
            steps {
                sh "cd Clase12-13"
            }
        }
        stage('Execute ansible') {
            steps {
                sh "ansible-playbook -i inventory.ini main.yml"
            }
        }
    }
}