pipeline {
    agent any
    stages {
        stage('SCM checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/edgaregonzalez/devops-63703.git'
            }
        }
        stage('Execute ansible') {
            steps {
                sh "ansible-playbook -i ./Clase12-13/inventory.ini ./Clase12-13/main.yml"
                
            }
        }
    }
}