
Vagrant.configure("2") do |config|

  # webserver configuration
  config.vm.define "webserver" do |web|
    web.vm.box = "ubuntu/lunar64"
    web.vm.network "public_network"
    web.vm.provision "shell", inline: <<-SHELL
      sudo useradd -m -s /bin/bash -p 'educacionit2023' ansible
      sudo usermod -aG sudo ansible
    SHELL
  end
  # dbserver configuration
  config.vm.define "dbserver" do |db|
    db.vm.box = "ubuntu/lunar64"
    db.vm.network "public_network"
    db.vm.provision "shell", inline: <<-SHELL
      sudo useradd -m -s /bin/bash -p 'educacionit2023' ansible
      sudo usermod -aG sudo ansible
    SHELL
  end

end
