name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub yugarcia
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: ${{ github.workspace }}/EjercicioClase32/api-rest/
        file: ${{ github.workspace }}/EjercicioClase32/api-rest/Dockerfile